Repository cnumr/ecoindex_cli, pull requests merged in 2021-11, with the labels that each got.

#78 fix(async): Update project to use async version
  README.md
  ecoindex_cli/cli/app.py
  poetry.lock
  pyproject.toml
Labels: fix

#83 Try except in asyncio
  ecoindex_cli/cli/app.py
  ecoindex_cli/cli/arguments_handler.py
  ecoindex_cli/files.py
  ecoindex_cli/logger.py
  ecoindex_cli/report/report.py
  tests/ecoindex_cli/cli/test_arguments_handler.py
Labels: feature

#88 chore(deps): Update project version and deps
  poetry.lock
  pyproject.toml
Labels: chore
